In [1]:
import pandas as pd
import numpy as np
from scipy.io import loadmat
import matplotlib.pyplot as plt
from sklearn.linear_model import SGDClassifier
from sklearn.multiclass import OneVsOneClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
import seaborn as sns 
from sklearn import datasets
from sklearn.model_selection import train_test_split ,StratifiedShuffleSplit , GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.feature_selection import SelectKBest,chi2,SelectPercentile,mutual_info_classif,f_classif
from scipy.stats import pearsonr

In [14]:
#Ex MultinomialNB
mnist_path = 'mnist-original.mat'

mnist = loadmat(mnist_path)
X = mnist['data'].T
y = mnist['label'][0]



X_new = SelectKBest(chi2, k=700).fit_transform(X, y)
X_new =SelectPercentile(f_classif, percentile=20).fit_transform(X_new, y)
#display(X_new)
#display(X_new / 255)
#X_new = X_new / 255
display(X_new.shape)

sss = StratifiedShuffleSplit(n_splits=10, test_size=0.15,train_size=0.85, random_state=0)
train_index, test_index = next(sss.split(X=X_new, y=y))   

X_train, X_test = X_new[train_index], X_new[test_index]
y_train, y_test = y[train_index], y[test_index]
display(X_train.shape,X_test.shape)

display(X.shape)
display(X_new.shape)
#np.corrcoef(X_new)



(70000, 140)

(59500, 140)

(10500, 140)

(70000, 784)

(70000, 140)

In [15]:
#Ex MultinomialNB

mnb = MultinomialNB() 
score_mnb = cross_val_score(mnb,X_train,y_train,cv=3)
display(score_mnb)

gnb = GaussianNB() 
score_gnb = cross_val_score(gnb,X_train,y_train,cv=3)
display(score_gnb)

voc_sgd = OneVsOneClassifier(SGDClassifier(random_state= 42))
score_voc_sgd = cross_val_score(voc_sgd,X_train,y_train,cv=3)
display(score_voc_sgd)
#gnb.fit(X_train,y_train)
#gnb.score(X_test,y_test)

array([0.75879802, 0.76266828, 0.7624666 ])

array([0.73711808, 0.73337367, 0.73907124])

array([0.85797116, 0.85272021, 0.84293854])

In [4]:
from sklearn.feature_selection import RFE
mnb = MultinomialNB() 
rfe = RFE(mnb, 100)
score_mnb = cross_val_score(rfe,X_train,y_train,cv=3)
display(score_mnb)

array([0.71271554, 0.71290274, 0.71476832])

In [9]:
1. grid search SelectKBest
2. grid search SelectPercentile

AttributeError: 'numpy.ndarray' object has no attribute 'items'