In [92]:
from sklearn import datasets
from sklearn.svm import SVC
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.io import loadmat
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import  StratifiedShuffleSplit,GridSearchCV
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.base import BaseEstimator

In [139]:
mnist_path = 'mnist-original.mat'

mnist = loadmat(mnist_path)
X = mnist['data'][:5].T
y = mnist['label'][:5][0]
display(X.shape , y.shape)

# Scale all X values
scaler = StandardScaler()
X_scaled  = scaler.fit_transform(X)

sss = StratifiedShuffleSplit(n_splits=10, test_size=0.0005,train_size=0.0005, random_state=0)
train_index, test_index = next(sss.split(X=X_scaled, y=y))   

X_train, X_test = X[train_index], X[test_index]
y_train, y_test = y[train_index], y[test_index]
display(X_train.shape,X_test.shape)

display(y_train[:5])
df_y_train = pd.get_dummies(y_train)
y_train = df_y_train.values
display(y_train[:5])

df_y_test = pd.get_dummies(y_test)
y_test = df_y_test.values


(70000, 5)

(70000,)

(35, 5)

(35, 5)

array([7., 7., 0., 1., 1.])

array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

In [268]:
class Perceptron(BaseEstimator):
    
    def __init__(self,random_state):
        self.random_state = random_state
        pass
    
    def fit(self,X,y):
        print(X,y)
            
        rng = np.random.RandomState(self.random_state)       
        self.weight_ = np.round(rng.normal(loc=0.0,scale=0.1,size=X.shape[0] + 1),4)
        self.net_ = self.net(X)
        self.O_ = sigmoid(self.net_)
            
        #print('weight_',self.weight_,'net_',self.net_,'O',self.O_)
        return self
    
    def net(self,X):
        return np.dot(X,self.weight_[1:]) + self.weight_[0]
    
    def sigmoid(value):
        print(value)
            
        return 1 / (1 + np.exp(value))

    
    

In [330]:
def mlp(data,target,n_hidden_layers=1,n_hidden_len = 2,n_iter=50):
    network = {} 
    outputs = {}
        
    all_layers = n_hidden_layers + 1 #includes output layer
    
    outputs = np.zeros(n_hidden_len)
    
    print('all_layers , includes output layer', all_layers)
        
    data = data[:n_iter]
    for idx, sample in enumerate(data):
        for layer in range(1,all_layers+1,1):
            for hidden_len in range(n_hidden_len):
                #print('sample',sample,'idx',idx,'layer',layer+1,'layer_len',layer_len)
                print('layer',layer,'Perceptron',hidden_len)
                if layer == 1:
                    P = Perceptron(42).fit(sample,target[idx])
                    print('[O_]',P.O_)
                    #key = str(layer) + ' ' + str(hidden_len)
                    network[layer] = P
                    outputs.append(P.O_)
                    
                else:
                    pass
                    #print('layer',layer)
                    #print(outputs[layer])
                    
                    #network[layer+1] = Perceptron(42).fit(np.array(outputs),target[idx])
                #propagate the inputs forward
                #propagate_forward(layer,sample)
            
    
    

In [331]:

mlp(X_train,y_train,1,2,2)

all_layers , includes output layer 2
layer 1 Perceptron 0
[0 0 0 0 0] [0 0 0 0 0 0 0 1 0 0]
[O_] 0.4875775569407687


NameError: name 'outputs' is not defined

In [287]:

range(2,4)

range(2, 4)