In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_digits
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error as mse
from sklearn.feature_selection import SelectKBest,chi2


### feature selection

In [11]:

X,y = load_digits(return_X_y=True)
X.shape ,y.shape
X
X_n = SelectKBest(chi2,k=20).fit_transform(X,y)

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [36]:
sum_all = 650
total_col = np.array([349,151,150])
ratios_cols = total_col/sum_all 
display('ratios_cols',ratios_cols)

expected_A = ratios_cols * 150 
display('expected_A',expected_A)
observed_A = np.array([90,30,30])
chi_squared_stat_A = (((observed_A-expected_A)**2)/expected_A).sum()
display('chi2_A',chi_squared_stat_A)


expected_B = ratios_cols * 150 
#display('expected_B',expected_B)
observed_B = np.array([60,50,40])
chi_squared_stat_B = (((observed_B-expected_B)**2)/expected_B).sum()
display('chi2_B',chi_squared_stat_B)

expected_C = ratios_cols * 200
#display('expected_C',expected_C)
observed_C = np.array([104,51,45])
chi_squared_stat_C = (((observed_C-expected_C)**2)/expected_C).sum()
display('chi2_C',chi_squared_stat_C)

expected_D = ratios_cols * 150
#display('expected_D',expected_D)
observed_D = np.array([95,20,35])
chi_squared_stat_D = (((observed_D-expected_D)**2)/expected_D).sum()
display('chi2_D',chi_squared_stat_D)



'ratios_cols'

array([0.53692308, 0.23230769, 0.23076923])

'expected_A'

array([80.53846154, 34.84615385, 34.61538462])

'chi2_A'

2.4008804721152197

'chi2_B'

12.665291983191755

'chi2_C'

0.5788511167194829

'chi2_D'

8.92617928655614